### PR TITLE
refactor ROS and update features.py

### PR DESCRIPTION
**Pull request by phobson**

### CODE REVIEW

**Comment by phobson** [comment]
@lucashtnguyen can you look at this?

**Comment by phobson** [comment]
@lucashtnguyen this has to go in now -- but please do still take a look when you get the chance.

**Comment by lucashtnguyen** [comment]
Okay, I'll see if I can fit this in today

**Comment by lucashtnguyen** [comment]
Looks good, nothing critical stuck out to me.

**Pull request merged**
